### ISSUE TITLE
Sunny 

### ISSUE THREAD

**Issue by nahcbr** [XMuli/SunnyPages#1]
Hi,
Sunny is very good. Congratulations on the excellent work.
I would like to suggest two resources:
1. Translation of the program into other languages (I propose to translate into Portuguese-Brazil);
2. Translation feature: offer other languages.
Thanks.
Nelson Carvalho

**Comment by XMuli** [comment]
Thank you very much for your feedback, but I'm not very good at this language.

Making the source file  `*.ts` available, and if interested, feel free to submit PRs for pt_BR, etc. 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

→ [translations Folder](https://github.com/XMuli/SunnyPages/tree/master/translations)

**Comment by nahcbr** [comment]
Thanks.
I will translate the file and send it to you.
