### ISSUE TITLE
Ubuntu 系统不兼任

### ISSUE THREAD

**Issue by inbjo** [XMuli/SunnyPages#10]
我的系统版本是  Ubuntu 22.04.4 LTS
安装[Sunny_ubuntu_22.04_1.3.0_x64.deb](https://github.com/XMuli/SunnyPages/releases/download/v1.3/Sunny_ubuntu_22.04_1.3.0_x64.deb) 运行无任何反应

使用[Sunny-ubuntu_22.04_x86_64.AppImage](https://github.com/XMuli/SunnyPages/releases/download/v1.3/Sunny-ubuntu_22.04_x86_64.AppImage)  可以运行右下角出现图标，点击截图整个屏幕黑屏（我是笔记本扩展了一个屏幕）

![Screenshot from 2024-03-20 15-02-09](https://github.com/XMuli/SunnyPages/assets/11854149/0a74912e-15cd-4c87-b177-a550b0127752)

![image](https://github.com/XMuli/SunnyPages/assets/11854149/37623597-b073-4554-a8ea-799801e8ce89)

**Comment by XMuli** [comment]
将 windowing system 的 `Wayland` 修改为为 `x11` 试一下？可能和这个有关

**Comment by XMuli** [comment]
当前 wanly 还在过渡阶段，x11 稳定性更好
![image](https://github.com/XMuli/SunnyPages/assets/33887845/f27e7b99-e8c3-490b-8b28-14d004cb2bdd)
