### ISSUE TITLE
配置无法保存，快捷键失效

### ISSUE THREAD

**Issue by m2cc** [XMuli/SunnyPages#12]
系统：deepin 20.9
1. 配置无法保存，每次都要重新设置
2. ocr快捷键无效
3. ocr识别后，希望可以直接复制文字到剪贴板

**Comment by XMuli** [comment]
1. 我会排查下
2. 改版之后，测试不完全没发现，感谢反馈🙇‍
3. 可以新增一个设置开关

预计下一个小版本恢复

**Comment by m2cc** [comment]
> 1. 我会排查下，已经在修复中
> 2. ocr是无快捷键的；改版之后，测试不完全，也会排查和修复，感谢反馈🙇‍
> 3. 可以新增一个设置开关
> 
> 预计下一个小版本恢复

感谢

**Comment by XMuli** [comment]
1. 已修复； 2；所有一级工具栏已添加 快捷键，OCR 为 `Ctrl +O`，悬浮预览可见； 3；待下版本更新；
可下载 [Release v1.5](https://github.com/XMuli/SunnyPages/releases)
![image](https://github.com/XMuli/SunnyPages/assets/33887845/727e5d1d-6da5-4773-90da-e29ccd6ad0d9)

**Comment by XMuli** [comment]
1. 已修复； 2；所有一级工具栏已添加 快捷键，OCR 为 `Ctrl +O`，悬浮预览可见； 3；待下版本更新或详聊提供定制包；
新版本已经发布；可下载 [Release v1.5](https://github.com/XMuli/SunnyPages/releases)

![image](https://github.com/XMuli/SunnyPages/assets/33887845/727e5d1d-6da5-4773-90da-e29ccd6ad0d9)

**Comment by m2cc** [comment]
> 1. 已修复； 2；所有一级工具栏已添加 快捷键，OCR 为 `Ctrl +O`，悬浮预览可见所有快捷键； 3；待下版本更新或详聊提供定制包；
>    新版本已经发布；可下载 [Release v1.5](https://github.com/XMuli/SunnyPages/releases)
> 
> ![image](https://private-user-images.githubusercontent.com/33887845/322706344-677ce0a6-96c8-49e3-8bd6-fd3f989e0b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzk3NDIsIm5iZiI6MTcxMzMzOTQ0MiwicGF0aCI6Ii8zMzg4Nzg0NS8zMjI3MDYzNDQtNjc3Y2UwYTYtOTZjOC00OWUzLThiZDYtZmQzZjk4OWUwYjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA3MzcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmVhYWViYzUzNzk5MzQwMTcxNzM5ZjY4NTNjNGJhYWM5MmFmYmM4Y2U2MzRmZmY5Yjk5YWNiYzMyNzdkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tD7tDLu3W6wM2VoR-4DN-6rGQZy4T5ImJtiEp6AaMvY)

你好，不知道是不是我使用的方式不对，配置还是无法保存。系统是deepin 20.9，下面我录了个屏。

![录屏_选择区域_20240417154018](https://github.com/XMuli/SunnyPages/assets/17061984/ac463b92-4e9e-4527-b58f-238df5cb6d6d)

**Comment by XMuli** [comment]
感谢反馈，已定位，属于linux 下的此路径下，此配置文件没有写入权限，下一个版本会彻底修复此问题。

**临时解决方案：** 使用管理管权限启动程序

**Comment by m2cc** [comment]
> 感谢反馈，已定位和修复，属于linux 下的此路径下，此配置文件没有写入权限；请重新在 [Release ](https://github.com/XMuli/SunnyPages/releases/tag/v1.5.0) （.deb 已经更新）下载新的文件即可；
> 
> Linux 下验证新版本方法，和下图日期一致即可： ![image](https://private-user-images.githubusercontent.com/33887845/323302944-48797fe0-5d89-4cc9-b952-e564f667c1a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDQzNzMsIm5iZiI6MTcxMzQwNDA3MywicGF0aCI6Ii8zMzg4Nzg0NS8zMjMzMDI5NDQtNDg3OTdmZTAtNWQ4OS00Y2M5LWI5NTItZTU2NGY2NjdjMWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAxMzQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2QxNGU0NTUzZmFlOTdmMDM4MjBhN2Q3MzUzN2ZjYmM5ZjI4YmVlYmM1NDBmZmVjNjhjNmU3MWZhZjllYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EQLXGBXDsq8UvnRsN1LS3fjSqWP4LavhKMbU43SV9qw)

感谢，确实好了

**Comment by XMuli** [comment]
已修复，见新的正式版本 [v1.6.2](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.2)
