### ISSUE TITLE
截图时选择的区域与结果区域不匹配

### ISSUE THREAD

**Issue by adventureRyan** [XMuli/SunnyPages#14]
我使用的是debian12，当选定好截图区域后，结果图并不是我选定的区域，有偏差

**Comment by XMuli** [comment]
可以发下详细软件和系统详细版本截图？ （x11 or wayland）

**Comment by XMuli** [comment]
感谢后续详细反馈，已修复，见新的正式版本 [v1.6.2](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.2)
