### ISSUE TITLE
图片默认格式问题

### ISSUE THREAD

**Issue by denzel668** [XMuli/SunnyPages#16]
截图时只有默认首选.png格式，建议加个手动保存jpg一次后默认为.jpg

**Comment by XMuli** [comment]
好的💖

**Comment by XMuli** [comment]
感谢反馈，已支持此功能，见新版本 [v1.6.2](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.2)

**Comment by denzel668** [comment]
辛苦啦,保存时可以变更默认格式了,但下面的保存类型没有一起变更,一起变更的话就完美了
![Sunny_2024-0521_032437](https://github.com/XMuli/SunnyPages/assets/58988454/73b818bb-b134-471d-9916-0db75606f51a)

**Comment by XMuli** [comment]
好的，多谢细节反馈

**Comment by XMuli** [comment]
好的，也会调整此细节的
