### ISSUE TITLE
内存占用高

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#17]
168MB

**Comment by XMuli** [comment]
可发下 sunny 和 系统的版本信息

**Comment by sonichy** [comment]
重启后44MB，奇怪了。

**Comment by XMuli** [comment]
那还是比较大，即使 64bit 一般也是 2~3MB 左右

![image](https://github.com/XMuli/SunnyPages/assets/33887845/cd2de304-02d8-48a8-ad8d-f9d5a96d8fa0)

**Comment by sonichy** [comment]
截图后又变大了。
https://s21.ax1x.com/2024/05/11/pketQhT.png

**Comment by XMuli** [comment]
这个开发时候注意到过，等一段时间后 qt 会合适时机自动释放

**Comment by XMuli** [comment]
分析详见文章 [如何开发一款截图软件呢？](https://sunny.xmuli.tech/article/how_develop_it.html#%E7%9C%8B%E4%B8%8D%E8%A7%81%E7%9A%84%E4%BC%98%E5%8C%96)  "看不见的优化 - Q1 "

**Comment by sonichy** [comment]
v1.6.2 稳定144MB
