### ISSUE TITLE
静默截图

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#18]
不需要保存操作，快捷键直接保存。
玩游戏，看电视，我用得很多，不影响观感。

**Comment by XMuli** [comment]
方案一：直接 `Ctrl + Shift + S` 可以快速保存，仅右下角弹出临时提示；
方案二：勾选自动保存，保存时候无任何提示

若是看看希望快捷键全屏直接保存，无任何提示；
- 离线视频用 PotPlayer，自带这个功能
- 网页看视频，这个需求可以评估下
- 游戏 xbox steam 好像也都自带这种功能

**Comment by sonichy** [comment]
Ctrl + Shift + S 无效。
勾选自动保存 无效
我玩云游戏的。

**Comment by XMuli** [comment]
这是新的测试版本
[Sunny_protable_1.6.2_内测版.zip](https://github.com/XMuli/SunnyPages/files/15286071/Sunny_protable_1.6.2_.zip)

**Comment by sonichy** [comment]
v1.6.2 仍然没有静默截图。

**Comment by XMuli** [comment]
> 方案一：直接 `Ctrl + Shift + S` 可以快速保存，仅右下角弹出临时提示； 方案二：勾选自动保存，保存时候无任何提示
> 
> 若是看看希望快捷键全屏直接保存，无任何提示；
> 
> * 离线视频用 PotPlayer，自带这个功能
> * 网页看视频，这个需求可以评估下
> * 游戏 xbox steam 好像也都自带这种功能

推荐使用此方法，静默截图需求比较大可以做
