### ISSUE TITLE
Tooltip没有翻译

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#19]

**Comment by XMuli** [comment]
下一版本会更新

**Comment by XMuli** [comment]
已更新部分翻译和葡萄牙语，见新的正式版本 [v1.6.2](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.2)；

翻译属于持久性性的，暂时关闭

**Comment by sonichy** [comment]
v1.6.2 仍然没有翻译。

**Comment by sonichy** [comment]
https://v.douyin.com/i2KAh3HA/
