### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [XMuli/SunnyPages#21]
Does this work with Win 7?

Thanks

**Comment by XMuli** [comment]
Thanks for the feedback, I'll debug it to run on win7!

**Comment by XMuli** [comment]
Try using the installer version, which automatically installs the required dependencies.  [Sunny_setup_1.6.2_x64.exe](https://github.com/XMuli/SunnyPages/releases/download/v1.6.2/Sunny_setup_1.6.2_x64.exe)
