### ISSUE TITLE
把各种截图命令加进托盘菜单

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#23]
无键盘，键盘部分按键失灵，快捷键冲突，也可以使用截图。

**Comment by XMuli** [comment]
![image](https://github.com/XMuli/SunnyPages/assets/33887845/8fc4140b-40d7-4f6c-aca6-049b7a5064ad)

**Comment by sonichy** [comment]
https://s21.ax1x.com/2024/05/22/pkMsVjs.jpg

**Comment by XMuli** [comment]
感谢建议
tray 的 item 默认第一个就是截图；另点击托盘图标，也可以触发截图。
其它命令截图，合适会加一部分到托盘菜单
