### ISSUE TITLE
Color crosshair problem

### ISSUE THREAD

**Issue by thiagodalsoto** [XMuli/SunnyPages#25]
In the interface when using Crosshair, color capture does not work, always taking the Crosshair color, when deactivating Crosshair everything works
![Peek 21-05-2024 09-18](https://github.com/XMuli/SunnyPages/assets/30872231/a70f40b4-861f-4626-8bf3-30dc9a9e4201)

**Comment by XMuli** [comment]
Thanks for the feedback, will look into fixing this bug!

**Comment by XMuli** [comment]
It has been fixed in  [v1.6.3](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.3)
