### ISSUE TITLE
v1.6.3 延时截图系统卡死

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#30]
Linux Devuan
过一会儿恢复，窗管异常。

**Comment by XMuli** [comment]
新版本 [v2.2.1](https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1) 已发布，**因延时截图和自定义截图的交互在重新设计中，暂时将延时截图和自定义截图从策略中移除。**
后续会添加回来；若有需要，可先使用 [v1.6.3](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.3) 版本;
