### ISSUE TITLE
快捷键设置和提示不一样

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#31]
快捷键延时截图和自定义截图反了。
文字也不一样，延时，延迟。
https://s21.ax1x.com/2024/05/31/pk8eyIx.png
快捷单键占用时（如F6），无法设置同样的复合键（Alt+F6）。

**Comment by XMuli** [comment]
感谢反馈，我排查下

**Comment by XMuli** [comment]
新版本 [v2.2.1](https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1) 已发布，暂时将延时截图和自定义截图从策略中移除。
后续会添加回来；若有需要，可先使用 [v1.6.3](https://github.com/XMuli/SunnyPages/releases/tag/v1.6.3) 版本
