### ISSUE TITLE
Appimage版本不能修改语言

### ISSUE THREAD

**Issue by sonichy** [XMuli/SunnyPages#32]
Arch Linux

**Comment by XMuli** [comment]
*.Appimage 打包较复杂，后续会继续研究下这块，thx

**Comment by XMuli** [comment]
exe，deb 主流都是支持切换语言；*.Appimage 精力原因，支持稍缓。

**Comment by XMuli** [comment]
已修复，请下载 [v3.1.2](https://github.com/XMuli/SunnyCapturer/releases/tag/v3.1.2) 体验
