### ISSUE TITLE
不支持wayland

### ISSUE THREAD

**Issue by hljhljhlj** [XMuli/SunnyPages#34]
wayland下面是空白

**Comment by XMuli** [comment]
当前 Linux 下仅支持 X11
 wayland 待稳定后会兼容支持

**Comment by OldSaltFish** [comment]
希望能够早日支持wayland，目前linux平台只有snipaste还能用用。而snipaste不支持动图录制，长截图，OCR等功能。所以我很期待这款软件。

**Comment by XMuli** [comment]
@OldSaltFish 感谢您的期待和关注，SunnyCapturer 目前已升级到 Qt6.x，对于 Qt6 抓取 linux wayland 模式存在权限问题。 需要后续继续 wayland 单独编写或者等待 Qt 升级这部分也支持也行。


**如果不是非必须的话 wayland，Linux 切换 x11 模式即可使用** [link](https://sunnycapturer.xmuli.tech/#/zh-cn/troubleshooting?id=linux)， 切换方式参见 

```bash
sudo vim /etc/gdm3/custom.conf
# 将 WaylandEnable=false 的这行注释解开
sudo systemctl restart gdm3  # 重启系统
```
