### ISSUE TITLE
OCR doesn't work

### ISSUE THREAD

**Issue by thiagodalsoto** [XMuli/SunnyPages#36]
A few days ago the OCR tool stopped working, when I click on it nothing happens, if I keep clicking it several times, there comes a point when I receive the feedback that the API has reached the daily usage limit, even though I haven't used it once. Error can be seen at the end of the gif.
![OCR error](https://github.com/XMuli/SunnyPages/assets/30872231/0ffef881-370d-4b80-ae41-d9560b6c929e)

**Comment by XMuli** [comment]
good moring, friend , with the increased use of the user population, access has reached the free cap; 
![31711210fc07636a3054cb63412fe8f2](https://github.com/XMuli/SunnyPages/assets/33887845/ef591c4c-ea20-4ff9-81d4-44ca4637529a)


**the solution is as follows:**
- Register a private account and replace the default tokens, Ref: release v1.3 and v1.4 note，and [wiki](https://github.com/XMuli/SunnyPages/wiki/6.-Image-Translation-&-OCR-%7C-%E5%9B%BE%E7%89%87%E7%BF%BB%E8%AF%91-&-%E6%96%87%E5%AD%97%E6%8F%90%E5%8F%96)
    If you can't register, contact me at xmulitech@gmail.com / [telegram](https://t.me/xmuli) and I'll help you or using it for you!
- On the 1st of every month, the OCR quota is reset.
- Wait for the next version to add offline OCR

**Comment by thiagodalsoto** [comment]
Good morning...
From the return message, I already imagined that it would be something related to the usage limit, with your tip, I'll try to create an account and use it :), and certainly an offline OCR resource would be the best pain in the world, thank you
