### ISSUE TITLE
Ubuntu 20.04无法使用

### ISSUE THREAD

**Issue by the-bule-sea** [XMuli/SunnyPages#37]
开发者你好。我的系统为Ubuntu 20.04.6 LTS（如下）。
![2024-07-09 15-28-48 的屏幕截图](https://github.com/XMuli/SunnyPages/assets/59384519/292922e4-948d-4844-8e55-78fe7f4ecc86)
试着下载了1.6.2和1.6.3的deb，安装成功，但是点击软件图标无任何反应。
![2024-07-09 15-32-13 的屏幕截图](https://github.com/XMuli/SunnyPages/assets/59384519/dcada603-dc9d-486e-bc02-3e08fb8532a0)

**Comment by XMuli** [comment]
删除 ~/.config/Sunny 文件夹，再重新安装最新 v1.6.3.deb 后，终端执行 Sunny，可发下日志截图

**Comment by the-bule-sea** [comment]
比较奇怪的是，.config目录下并未出现/Sunny 文件夹，重新安装v1.6.3.deb后也未出现
![2024-07-10_15-04-25](https://github.com/XMuli/SunnyPages/assets/59384519/5e7938b9-10f3-4612-a711-9b39d74e816d)

**Comment by XMuli** [comment]
终端执行 Sunny，就会自动生成配置文件，同时有信息，可截图看一下
XMuli Tech
***@***.*** 
---- Replied Message ----
***@***.***>Date07/10/2024 15:07 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [XMuli/SunnyPages] Ubuntu 20.04无法使用 (Issue #37)
比较奇怪的是，.config目录下并未出现/Sunny 文件夹，重新安装v1.6.3.deb后也未出现
2024-07-10_15-04-25.png (view on web)

**Comment by XMuli** [comment]
索嘎， 看来是 ubuntu20.04 apt 里面的 qt 库版本太低了； 
可以试试 [Sunny_1.6.3.AppImage](https://github.com/XMuli/SunnyPages/releases/download/v1.6.3/Sunny_1.6.3.AppImage) 格式的，

或后面有空我用 ubuntu20.04 尝试编译一个低版本依赖的试下
