### ISSUE TITLE
Feature Request: Add Long Screenshot Capability

### ISSUE THREAD

**Issue by REDPAUI** [XMuli/SunnyPages#38]
当前软件不支持长截图功能，这对于需要捕捉网页或文档全貌的用户来说是一个限制。长截图功能将允许用户滚动屏幕并捕捉整个视图，而不仅仅是当前屏幕显示的部分。

**Comment by XMuli** [comment]
长截图需求会在其他功能完善后支持，参考 #3  二楼

**Comment by XMuli** [comment]
update: 长截图核心功能已实现，待后续版本集成。且新的回复会在 #3 中更新，对于重复或类似的 ISSUES 会在第一个中进行讨论
