### ISSUE TITLE
sunny有一些特殊的符号比如下划线识别不了

### ISSUE THREAD

**Issue by 66Coding** [XMuli/SunnyPages#4]
![001](https://github.com/XMuli/SunnyPages/assets/95664201/3309b037-f719-43ec-9021-e59c46ae0603)
_  下划线识别不了，数学特殊符号也识别不了

![002](https://github.com/XMuli/SunnyPages/assets/95664201/3a86a997-30b6-451d-b675-ef93b0af095e)
这个复制按钮为什么要弄两个，最前面的那个还复制不了

![003](https://github.com/XMuli/SunnyPages/assets/95664201/ea361863-d565-4575-9859-5b75e12638ea)
这个点复制没用，不知道复制到哪里去了，粘贴不出来

OCR能展示两屏吗，一屏展示原图，一屏展示识别的内容，这样方便对比，哪里识别有错误

**Comment by 66Coding** [comment]
一般ocr识图都不会超过半个屏幕的，都是识别一小部分的，至少我目前为止还没有识别过全屏或者半屏的，可不可以，低于半屏的，就显示对比，然后超过半屏的，就显示全的，或者可以自已自定义要不要把两屏显示出来

**Comment by 66Coding** [comment]
可以参考下QQ的ocr识图吗，我觉得那个就做的挺好的，除了他有分段复制不小心点到了麻烦，我对比了下，qq的ocr虽然也准确，但你这个好像比qq的还更准确点

**Comment by XMuli** [comment]
弹窗且缩小截取区域图片，有一个对比原图是个好的且可行想法

**Comment by XMuli** [comment]
@66Coding 弹出式窗口的 OCR，已发布于 [v1.4.0](https://github.com/XMuli/SunnyPages/releases/tag/v1.4.0)

**Comment by 66Coding** [comment]
这个自动换行太多了，我复制过去
![image](https://github.com/XMuli/SunnyPages/assets/95664201/20ba7ee2-bdd2-4cd1-a1e5-1bd0f4caa42a)
他给我翻译的是这样的
然后 我想要左边的结果，他给我输出右边的结果，要我手动改格式，能不能再调调
![image](https://github.com/XMuli/SunnyPages/assets/95664201/d6959345-2f52-43d1-ac05-f61412724acf)

**Comment by XMuli** [comment]
- 上图的效果测试来看，Sunny OCR 和 QQ 截图格式一致，但识别准略率比QQ更高，见红框
![image](https://github.com/XMuli/SunnyPages/assets/33887845/c3585ee6-6285-4334-aaac-b37a935095e2)

> 然后 我想要左边的结果，他给我输出右边的结果，要我手动改格式，能不能再调调

猜测右侧为你写的 java 程序输出，但是统一用换行`\n` ；而左侧的输出效果，它是输出格式做了调整，同时 **采用空格` `和换行`\n`** (或者`格式对齐`)，所以排版比右侧更加；修改你的输出格式即可。而非将换行通过 OCR 切换为你所想要的一张格式

**Comment by 66Coding** [comment]
coding_666@163.com ，单独发一个包谢谢啦

**Comment by 66Coding** [comment]
对，我也发现这个识别比QQ更准确，所以用的是sunny，我看你加了个有道的识别接口 ，这两个对比咋样哪个更准

**Comment by XMuli** [comment]
> 单独发一个包谢谢啦

可以详聊一下需求，评估下，若顺带的事情帮助实现

**Comment by 66Coding** [comment]
给个联系方式？

**Comment by XMuli** [comment]
WeChat: 252311126

**Comment by 66Coding** [comment]
加了

**Comment by XMuli** [comment]
效果如下，格式已对齐：
<img width="1407" alt="bc675eebf17321f618fdf897a0cc436" src="https://github.com/XMuli/SunnyPages/assets/33887845/a9f19374-aa8c-49a8-9c6f-8dbfde0aa2c0">

**参数：**
<img width="171" alt="630994b7fb20b76b07d90cec443568a" src="https://github.com/XMuli/SunnyPages/assets/33887845/fe01ec3e-ea3d-4fa2-bef6-4e22646d9415">
- 选用带 _local 的即可
- 可修改 xconfig.json  的 `tokens-advanced_ocr_baidu_align_rang` 提升识别率；


[Sunny_protable_1.5.0_x64.zip](https://github.com/XMuli/SunnyPages/files/14965398/Sunny_protable_1.5.0_x64.zip)
解压密码：3Q3MKMZTMXPha5gj

**Comment by 66Coding** [comment]
好，感谢
