### ISSUE TITLE
如何在 Arch linux 下面安装这个包？

### ISSUE THREAD

**Issue by zw963** [XMuli/SunnyPages#41]
Sunny 这个名字太普通了， 我竟然找不到 aur 源， 请指教。谢谢。

另外问一下， 是否支持 GNOME + Wayland 下面截图？ 类似于 flameshot ?

谢谢。

**Comment by zw963** [comment]
试了下 AppImage 版本， 似乎在 GNOME 46 + Wayland 下无法截图？

**Comment by XMuli** [comment]
你好，因没上传 aur 源到 archlinux 上；
暂仅支持 x11； 
重复 #39  #10

**Comment by XMuli** [comment]
名同身边的 life's cat； 也可 `桑尼`
