### ISSUE TITLE
appimage能否支持一下centos7

### ISSUE THREAD

**Issue by chantsing** [XMuli/SunnyPages#43]
您好，请问appimage能否支持一下centos7,因为电脑只支持到这个系统，而且没有管理员权限

**Comment by XMuli** [comment]
Sunny 运行是不需要 admin 权限的，可以使用全部功能（Win 是如此， 理论 Linux 同理）；

appimage 对 centos 7 的支持，我需要复现和评估后下，若是相对容易，也会一起支持的；  （但 理论上 appimage  是支持所有发行版的）

**Comment by XMuli** [comment]
新版本 [v2.2.1](https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1) 已发布；您可试下 [sunny-x64.AppImage](https://github.com/XMuli/SunnyPages/releases/download/v2.2.1/sunny-x64.AppImage) ，理论上上可在  centos 7 运行的，且不需要任何管理员权限

**Comment by chantsing** [comment]
不好意思，问题描述错了，centos版本很久了，他基础依赖版本太低，运行appimage会提示glibc库未找到😭
________________________________
发件人: XMuli ***@***.***>
发送时间: 2024年9月21日 11:45
收件人: XMuli/SunnyPages ***@***.***>
抄送: chantsing ***@***.***>; Author ***@***.***>
主题: Re: [XMuli/SunnyPages] appimage能否支持一下centos7 (Issue #43)


新版本 v2.2.1<https://github.com/XMuli/SunnyPages/releases/tag/v2.2.1> 已发布；您可试下 sunny-x64.AppImage<https://github.com/XMuli/SunnyPages/releases/download/v2.2.1/sunny-x64.AppImage> ，理论上上可在 centos 7 运行的，且不需要任何管理员权限

**Comment by XMuli** [comment]
一个参考的解决方案需自行源码编译高版本的 qt >= 5.15
![bcdd2b605839fc1bf4b9606ac26d99bd](https://github.com/user-attachments/assets/05c7412c-1c9c-4a51-92cb-341cb09a75bd)

**Comment by XMuli** [comment]
经过如下尝试：（yum 替换 aliy 的； ustc 已删除）

1. yum 默认自带的最高 qt5.9，版本过低
2. 无法在线安装 qt 5.15.2+， 会 so 报错缺少，补齐依赖后会提示 升级glibc，棘手且修改后对其它其它 centos 也不具有通用性
![136f01200b20942a635c1e9176169cc3](https://github.com/user-attachments/assets/e04744dc-71d5-4957-9ae3-936d09dcdeef)

4. 通过离线安装包最高安装 qt5.14；可运行，但是创建空项目也排不起来
5. cmake 最低 3.5，但 centos7 默认是 2.8，虽可手动修改 cmakelist.txt , 但是实测依旧无法编译；
    
![e6b4a4101d79172b90c2fd02e450d619](https://github.com/user-attachments/assets/77a6eab7-42f2-4875-b51f-b59847f50bfc)

7. sunny 无法在较低版本的 qt 版本编译和构建


经多种方法尝试，建议尝试其它替代版本软件，或切换已放弃的此 Linux 发行版。

**Comment by XMuli** [comment]
https://github.com/SunnyScreenshot/FLIPPED  这是 sunny 前身，完全 MIT 开源，你可以自己在  centos7 上自行魔改编译。  若你可以成功运行 flipped，那么 sunny 也就可以在这上面运行了。
