### ISSUE TITLE
多屏幕下截图会卡住无响应

### ISSUE THREAD

**Issue by 1xiaofeng1** [XMuli/SunnyPages#44]
您好，在多屏幕下，使用快捷键启动截图，会卡住无响应，系统是windows 11家庭版

**Comment by XMuli** [comment]
是会快捷键冲突了吗，导致被其他程序调用了?

理论上不会卡住，可在 [QQ: 418103279](https://qm.qq.com/cgi-bin/qm/qr?authKey=5pYNrJL7%2F8biKzT5LMj8dbjkpPvUvdLVbAOcNTydiqTDNc49yg0wtVcub8Cu3Pqa&k=OluWZhjVMhwP-6RO9Y7FFkJcXGiS4CVk&noverify=0) 中提供更详细的日志；

**Comment by 1xiaofeng1** [comment]
> 是会快捷键冲突了吗，导致被其他程序调用了?
> 
> 理论上不会卡住，可在 [QQ: 418103279](https://qm.qq.com/cgi-bin/qm/qr?authKey=5pYNrJL7%2F8biKzT5LMj8dbjkpPvUvdLVbAOcNTydiqTDNc49yg0wtVcub8Cu3Pqa&k=OluWZhjVMhwP-6RO9Y7FFkJcXGiS4CVk&noverify=0) 中提供更详细的日志；

我找到原因了，应该是和另外一个软件有兼容性问题，不开那个软件就没问题，谢谢
