### ISSUE TITLE
two question

### ISSUE THREAD

**Issue by passwa11** [XMuli/SunnyPages#46]
Q1: the border width can't canel or 0px

![image](https://github.com/user-attachments/assets/e5ba88c2-347c-444a-8a62-56029f9ba0e5)

Q2: can't change key binding at the ubuntu 

![image](https://github.com/user-attachments/assets/d25dc4dc-cd36-4f70-b03f-7f4a5019453b)

**Comment by XMuli** [comment]
A1：By design, a value of 0 means that the border is not displayed and is meaningless.
A2：If means disabled can't be changed; because Linux offline OCR is not supported for the time being, it is forbidden to use it. This feature will be developed in a later version

**Comment by passwa11** [comment]
> A1：By design, a value of 0 means that the border is not displayed and is meaningless. A2：If means disabled can't be changed; because Linux offline OCR is not supported for the time being, it is forbidden to use it. This feature will be developed in a later version

Q1: Maybe leaving an option to disable it would make the design more user-friendly.

Q2: If the system does not support it being disabled, a blank key binding should be set instead of a default value that cannot be changed, as this could cause conflicts with other software key bindings.

**Comment by XMuli** [comment]
yes，you are right. Next version I'll use empty as a binding without setting any hotkeys. Thanks for the suggestion.

**Comment by passwa11** [comment]
> yes，you are right. Next version I'll use empty as a binding without setting any hotkeys. Thanks for the suggestion.

Thank you for considering my second suggestion and deciding to use an empty binding without setting any hotkeys in the next version.

However, regarding the first suggestion, I still believe that providing an option to disable the feature would make the design more user-friendly. I hope you will reconsider this in a future update as well. Thanks again for your attention!

**Comment by passwa11** [comment]
can't disable it. all the keybords-box is grey like 
![image](https://github.com/user-attachments/assets/324c813b-2d43-4804-a2b8-85affcf82340)
