### ISSUE TITLE
暗色模式下图标看不清

### ISSUE THREAD

**Issue by yezibunengchi** [XMuli/SunnyPages#49]
![image](https://github.com/user-attachments/assets/42b67267-b7da-440c-838e-6ce86dd7b9ec)

**Comment by XMuli** [comment]
详细的运行环境是？

**Comment by yezibunengchi** [comment]
![image](https://github.com/user-attachments/assets/92c1258b-4c58-4932-9286-93d1680000f9)
![image](https://github.com/user-attachments/assets/5108d8a3-840d-415e-b651-ee5ef5a60218)
plasma桌面下的微风深色主题

**Comment by XMuli** [comment]
方便截图一下操作系统 设置里面的关于？ 
kde 等版本都显示出来
XMuli Tech
***@***.*** 
---- Replied Message ----
***@***.***>Date10/09/2024 10:48 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [XMuli/SunnyPages] 暗色模式下图标看不清 (Issue #49)
image.png (view on web)
image.png (view on web)
plasma桌面下的微风深色主题

**Comment by XMuli** [comment]
好的，下个版本修复

**Comment by XMuli** [comment]
已修复，新版本已发布 [v2.3](https://github.com/XMuli/SunnyPages/releases/tag/v2.3) ，可下载查看。
