### ISSUE TITLE
win ms store 中没有啊

### ISSUE THREAD

**Issue by Aurorxa** [XMuli/SunnyPages#5]
![image](https://github.com/XMuli/SunnyPages/assets/25677587/2af61f91-7204-46e9-bb8f-a43d040982e5)

**Comment by XMuli** [comment]
Microsoft Store down 方式，目前仅对指定的用户范围开放使用。

**Microsoft Store：**
![microsoft_store](https://github.com/XMuli/SunnyPages/assets/33887845/a40ded3f-abd4-40b2-a5ab-31c08528f1ab)


**Web Microsoft Store：**
![Web_microsoft_store](https://github.com/XMuli/SunnyPages/assets/33887845/d0365ee1-658d-4607-8d58-bdec3aa786e6)
