### ISSUE TITLE
截图启动时有点卡顿

### ISSUE THREAD

**Issue by wangdemon** [XMuli/SunnyPages#50]

**Comment by XMuli** [comment]
运行环境，版本详细信息方便的话，可补充一下？

**Comment by wangdemon** [comment]
v2.2.1 离线版

运行环境：win10企业版

效果视频如下，分别是SunnyPages截图和微信截图

https://github.com/user-attachments/assets/b67af9ab-1af4-481e-998a-09e2681a0519

**Comment by XMuli** [comment]
已修复，新版本已发布 [v2.3](https://github.com/XMuli/SunnyPages/releases/tag/v2.3) ，可以在这里设置为 “经典算法” 或 “关闭”，会得到更快的响应速度

![image](https://github.com/user-attachments/assets/5bf9df41-4f69-4753-b11f-2f73c109c59c)
