### ISSUE TITLE
Add delay, on click

### ISSUE THREAD

**Issue by thiagodalsoto** [XMuli/SunnyPages#52]
It would be interesting to have a delay of about 2 seconds after clicking capture so that the Sunny menu is not caught in the capture, thus disrupting the final result, this occurs in Ubuntu 24.04
![image](https://github.com/user-attachments/assets/7ba5ce1e-b2ef-4381-b252-d6282e394dd5)

Because the function is immediate, look at the print result
![Peek 18-10-2024 16-00](https://github.com/user-attachments/assets/d331007f-4c36-4cb8-af6a-dd998f209b79)

**Comment by XMuli** [comment]
```python
"shortcuts": {
        "disable": false,
        "delay_capture_time_s": 5,
        "capture": "F1",
        "delay_capture": "Ctrl+Shift+F1",
        "scroll_capture": "",
        "image_translate_capture": "Shift+F1",
        "extract_text_capture": "Alt+F1",
        "open_extract_text": "Ctrl+Shift+T"
    },
```


In the configuration xconfig.json file, you can modify the default delay time of screenshot, which is 5S by default.

`"delay_capture_time_s": 5,`

**Comment by thiagodalsoto** [comment]
solved, thanks
