### ISSUE TITLE
截图选择全屏时，工具栏也会被截图截进去。

### ISSUE THREAD

**Issue by the-bule-sea** [XMuli/SunnyPages#54]
## 首先很感谢作者大大开发出这么好用的工具，离线ocr真的很棒！
sunny版本：https://github.com/XMuli/SunnyPages/releases/download/v2.3/sunny_setup_2.3.0_x64_offline_ocr_cpu.exe
### 问题2：截屏时按C复制颜色无效、按shift切换颜色格式无效。这个不知道怎么录，就没图片了。
![Sunny_2024-11-05_22-15-49](https://github.com/user-attachments/assets/ab79e237-3f0d-4abb-8f46-e15eabb1dc44)

**Comment by XMuli** [comment]
1. 确实，会fix
2. 也会 fix 代码
预计下一个版本修复

**Comment by XMuli** [comment]
[sunny_win_2.4_beta_1108.zip](https://github.com/user-attachments/files/17680670/sunny_win_2.4_beta_1108.zip)

已修复，可提前预览效果，若是需要使用离线 OCR， 将此所有文件替换到 `[sunny_setup_2.3.0_x64_offline_ocr_cpu.exe` 的安装路径即可

**Comment by XMuli** [comment]
已修复在 [v2.4](https://github.com/XMuli/SunnyPages/releases/tag/v2.4)
