### ISSUE TITLE
win11兼容性问题

### ISSUE THREAD

**Issue by melrisic** [XMuli/SunnyPages#57]
大佬,这个软件的功能已经做的很简洁很好了,但是我用了半个月,发现我win11系统打开的第一次截屏,总是要等2-3秒,才能唤出截屏功能,后续正常,我有点强迫症,能不能帮忙修复一下

**Comment by XMuli** [comment]
设置 - 窗口检测模式 - 切换为 经典算法或者关闭试一下

**Comment by XMuli** [comment]
[v2.4](https://github.com/XMuli/SunnyPages/releases/tag/v2.4) 也已发布，可以再试试
