### ISSUE TITLE
火山\阿里云图片翻译有免费额度

### ISSUE THREAD

**Issue by uzcool** [XMuli/SunnyPages#6]
https://www.volcengine.com/docs/4640/68515 

https://help.aliyun.com/zh/machine-translation/product-overview/pricing-of-image-translation

![PixPin_2024-03-01_14-43-16](https://github.com/XMuli/SunnyPages/assets/38136975/1ac22c26-2b90-4aa3-9fb6-c7b5a12839a9)

其实可以设置个使用的计数.超过100次就停止..让不想付费的用户有个白嫖的额度..

或者使用一些免费的字符翻译额度先ocr直接字符翻译..会费用低些..也有免费额度

**Comment by XMuli** [comment]
我看下文档，争取下一个大版本 提供多个平台切换 [图片翻译和OCR]，另外 #4 准备做成类似于弹窗的形式，觉着效果可能回更好些？

<img src="https://github.com/XMuli/SunnyPages/assets/33887845/5d3b2cc7-c573-46c5-956e-61e39d6e193d" width="30%"/>

**Comment by XMuli** [comment]
[v1.4](https://github.com/XMuli/SunnyPages/releases) 版本已更新，[Wiki](https://github.com/XMuli/SunnyPages/wiki/6.-Image-Translation-&-OCR-%7C-%E5%9B%BE%E7%89%87%E7%BF%BB%E8%AF%91-&-%E6%96%87%E5%AD%97%E6%8F%90%E5%8F%96)

**支持线路切换，"OCR"和"图片识别"，已提升识别次数**
- OCR 次数提升至 3500次/月
- 图片识别次数提升为 10000次/年 + 其它

![image](https://github.com/XMuli/SunnyPages/assets/33887845/0ec95800-2694-494a-973e-246ae3d4ccd9)
